{
    "name": "Interest Management",
    "version": "15.0.1.0.0",
    "summary": "Manage Interest Rates and Calculations",
    "sequence": 10,
    "description": "Module to manage interest rates, rules, and calculations for invoices.",
    "category": "Accounting",
    "website": "https://dmunoz2019.github.io/diegoweb/",
    "license": "LGPL-3",
    "author": "Diego A. Muñoz",
    "depends": ["base", "account"],
    "data": [
        "views/rate_period_tree_view.xml",
        "views/rate_period_form_view.xml",
        "views/rate_period_kanban_view.xml",
        "views/rate_period_pivot_view.xml",
        "views/rate_period_graph_view.xml",
        "views/rule_tree_view.xml",
        "views/rule_form_view.xml",
        "views/rule_kanban_view.xml",
        "views/rule_pivot_view.xml",
        "views/rule_graph_view.xml",
        "views/line_tree_view.xml",
        "views/line_form_view.xml",
        "views/line_kanban_view.xml",
        "views/line_pivot_view.xml",
        "views/line_graph_view.xml",
        "views/interest_menus.xml",
        "views/account_move_form_view.xml",
        "security/ir.model.access.csv",
        "data/cron.xml",
        "data/data.xml",
    ],
    "demo": [],
    "installable": True,
    "application": True,
    "auto_install": False
}
